const HXI_FR = {
  "info" : {
    "title" : "HXI",
    "participantid" : "ID du.de la Participant.e : ",
    "back" : "< Retour",
    "instructions" : "Une série de déclarations vous sera présentée. Veuillez sélectionner l'option qui reflète le mieux votre niveau d'accord avec chaque énoncé concernant votre expérience avec la simulation.",
    "clarityDescription" : "Pour plus de clarté, veuillez consulter les définitions suivantes :",
    "hapticSensationsDefinition" : "Sensations haptiques : Tout ce que vous ressentez avec le sens du toucher. Il peut s'agir de vibrations, de force, de température, de pression ou de toute autre sensation physique.",
    "otherSensesDefinition" : "Autres sens : modalités sensorielles au-delà du toucher, telles que la vision et l'ouïe.",
    "understood" : "J'ai compris",
    "submit" : "Soumettre",
    "savedResponse" : "Votre réponse a bien été enregistrée.",
    "thankyou" : "Merci de votre participation!",
    "sendAnotherResponse" : "Envoyer une autre réponse",
    },
  "agreementLevel" :[
    "Fortement en désaccord",
    "En désaccord",
    "Plutôt en désaccord",
    "Ni d’accord ni en désaccord",
    "Plutôt d’accord",
    "D’accord",
    "Tout à fait d’accord"
  ],
  "questions" : 
  [{"0" : "Les sensations haptiques imitaient fidèlement les expériences auxquelles je m'attendrais dans la réalité."},
  {"1" : "Les interactions haptiques m'ont rendu plus concentré.e."},
  {"2" : "J'ai apprécié les sensations haptiques elles-mêmes."},
  {"3" : "Les sensations haptiques semblaient manquer de coordination avec les autres sens."},
  {"4" : "Les sensations haptiques semblaient familières au toucher réel."},
  {"5" : "J'ai trouvé que les sensations haptiques renforçaient mon engagement avec le système."},
  {"6" : "J'ai ressenti une déconnexion entre les sensations haptiques et les autres sens."},
  {"7" : "Les sensations haptiques fournissaient une représentation fidèle des sensations du monde réel."},
  {"8" : "Les sensations haptiques complémentaient bien les autres sens."},
  {"9" : "Les sensations haptiques semblaient désynchronisées par rapport aux autres sens."},
  {"10" : "J’ai l’impression que les sensations haptiques étaient bien coordonnées avec les autres sens."},
  {"11" : "Les sensations haptiques étaient agréables en elles-mêmes, indépendamment de leur fonction."},
  {"12" : "Les sensations haptiques ont contribué à mon implication dans la tâche."},
  {"13" : "Faire l’expérience des sensations haptiques était agréable pour moi."},
  {"14" : "J'ai ressenti une déconnexion entre les sensations haptiques et ce à quoi je m'attendais."},
  {"15" : "Les sensations haptiques s'intégraient de manière fluide aux autres sens."},
  {"16" : "Les sensations haptiques ressemblaient à celles que je ressens dans la vraie vie."},
  {"17" : "Je me sentais absorbé.e par la tâche en raison des sensations haptiques."},
  {"18" : "Indépendamment de leur fonction, j'ai trouvé les sensations haptiques plaisantes."},
  {"19" : "J'ai ressenti une sensation d'harmonie entre les sensations haptiques et les autres sens."}]
}
export default HXI_FR;